FROM alpine:3.20.3

ARG POSTGRESQL_MAJOR_VERSION
ARG POSTGRESQL_MINOR_VERSION

RUN apk --update --no-cache add "postgresql${POSTGRESQL_MAJOR_VERSION}-client=~${POSTGRESQL_MAJOR_VERSION}.${POSTGRESQL_MINOR_VERSION}" bash

WORKDIR "/"

ENTRYPOINT [ "/bin/bash" ]
